[build]
  base = "."
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Serve static assets first, then fallback to SPA
[[redirects]]
  from = "/styles.css"
  to = "/styles.css"
  status = 200

[[redirects]]
  from = "/workflow.js"
  to = "/workflow.js"
  status = 200

[[redirects]]
  from = "/app.js"
  to = "/app.js"
  status = 200

[[redirects]]
  from = "/auth.js"
  to = "/auth.js"
  status = 200

[[redirects]]
  from = "/cue.js"
  to = "/cue.js"
  status = 200

[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200

[[redirects]]
  from = "/icons/*"
  to = "/icons/:splat"
  status = 200

[[redirects]]
  from = "/new-pwa/*"
  to = "/new-pwa/:splat"
  status = 200

# SPA fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Force cache invalidation
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
