import {
  AudioLines,
  BookOpen,
  Clapperboard,
  FileText,
  Gauge,
  GitBranch,
  Languages,
  Layers,
  Library,
  ListTree,
  Map,
  Maximize2,
  Mic,
  MonitorPlay,
  PenLine,
  Radar,
  Share2,
  SlidersHorizontal,
  Smartphone,
  Wallet,
  Youtube,
  Zap,
  KeyRound,
  type LucideIcon,
} from 'lucide-react'
import { ASSISTANT_ICON } from '@/lib/constants/assistantIcon'

/** Icon map for Key Features cards — keys must match keyFeatures room feature icons. */
export const FEATURE_ICONS: Record<string, LucideIcon> = {
  seasonUniverse: Layers,
  episodeHandoff: ListTree,
  reshapeSeries: PenLine,
  directEpisode: Mic,
  treatment: Map,
  blueprintResonance: Gauge,
  blueprintDirector: ASSISTANT_ICON,
  stakeholderReview: Share2,
  byok: KeyRound,
  budget: Wallet,
  writersRoom: BookOpen,
  scriptResonance: Radar,
  sceneDirector: ASSISTANT_ICON,
  scriptDirector: FileText,
  referenceLibrary: Library,
  productionAgents: Zap,
  directShot: Clapperboard,
  preVis: MonitorPlay,
  mixer: SlidersHorizontal,
  languageStreams: Languages,
  deliveryResolution: Maximize2,
  versionControl: GitBranch,
  promoTrailer: Smartphone,
  screeningPlayer: AudioLines,
  screeningCollab: Share2,
  packageShip: Youtube,
}

export const KEY_FEATURE_ICON_KEYS = Object.keys(FEATURE_ICONS)
