import { ScriptData } from '@/lib/types/reports'
import React from 'react'

interface RendererProps {
  data: ScriptData
}

export const ScriptRenderer = React.forwardRef<HTMLDivElement, RendererProps>(({ data }, ref) => {
  return (
    <div ref={ref} className="script-wrapper">
      <style>{`
        @media print {
          @page {
            size: letter;
            margin: 0.75in 1in 0.75in 1in;
            counter-increment: page;
          }
          
          .script-wrapper {
            position: relative;
          }
          
          /* Page counter in top-right */
          .script-wrapper::before {
            content: counter(page) ".";
            position: running(page-header);
            font-family: 'Courier New', monospace;
            font-size: 12pt;
            text-align: right;
            width: 100%;
          }
          
          /* Footer branding */
          .script-footer {
            position: running(script-footer);
            text-align: center;
            font-family: 'Courier New', monospace;
            font-size: 10pt;
            color: #666 !important;
            padding-top: 0.5in;
          }
          
          .script-content {
            padding-top: 0.75in;
            padding-bottom: 0.75in;
          }
        }
        
        /* Page breaks */
        @media print {
          .scene-block {
            page-break-inside: avoid;
            margin-bottom: 1.5em;
          }
          
          .scene-heading {
            page-break-after: avoid;
          }
        }
      `}</style>
      <div className="script-content">
        <div className="report-container script-format p-8 font-mono !text-black bg-white text-sm">
          <div className="text-center mb-12">
            <h1 className="text-2xl underline !text-black">{data.title?.toUpperCase() || 'UNTITLED'}</h1>
            {data.author && <p className="mt-2 !text-black">by {data.author}</p>}
          </div>
          
          {data.script?.scenes?.map((scene, sIndex) => (
            <div key={sIndex} className="scene-block mb-6 print:break-inside-avoid">
              {/* Scene Heading */}
              {scene.heading && (
                <h2 className="font-bold mb-2 scene-heading !text-black">
                  {typeof scene.heading === 'string' ? scene.heading.toUpperCase() : scene.heading.text.toUpperCase()}
                </h2>
              )}
              
              {/* Visual Description / Action */}
              {scene.visualDescription && (
                <p className="mb-4 whitespace-pre-wrap !text-black">{scene.visualDescription}</p>
              )}
              {scene.action && (
                <p className="mb-4 whitespace-pre-wrap !text-black">{scene.action}</p>
              )}
              
              {/* Dialogue */}
              {scene.dialogue?.map((d: any, dIndex: number) => {
                // Handle both 'text' and 'line' fields (data uses 'line')
                const dialogueText = d.text || d.line || ''
                return (
                  <div key={dIndex} className="mb-4">
                    <p className="mt-4 mb-0 ml-[35%] !text-black">{d.character.toUpperCase()}</p>
                    {d.parenthetical && (
                      <p className="mb-0 ml-[30%] !text-black">({d.parenthetical})</p>
                    )}
                    <p className="mb-0 ml-[25%] mr-[15%] whitespace-pre-wrap !text-black">{dialogueText}</p>
                  </div>
                )
              })}
            </div>
          ))}
        </div>
      </div>
      <div className="script-footer">Generated by SceneFlow AI</div>
    </div>
  )
})

ScriptRenderer.displayName = 'ScriptRenderer'

