import type { VisualReference } from '@/types/visionReferences'
import type { SegmentDirection } from '@/types/scene-direction'

export type SceneSegmentStatus = 'DRAFT' | 'READY' | 'GENERATING' | 'COMPLETE' | 'UPLOADED' | 'ERROR'

// ============================================================================
// Scene Context Types (AI-enhanced scene details)
// ============================================================================

/**
 * Enhanced scene context generated by AI
 * Provides storytelling context for the user without being a production asset
 */
export interface SceneContext {
  /** The narrative beat this scene represents (e.g., "Inciting incident", "Rising action") */
  beat?: string
  /** How characters evolve in this scene (e.g., "Hero realizes their weakness") */
  characterArc?: string
  /** Thematic elements explored (e.g., "Sacrifice vs self-preservation") */
  thematicContext?: string
  /** ISO timestamp of when context was generated */
  generatedAt?: string
}

// ============================================================================
// Keyframe State Machine Types
// ============================================================================

/**
 * Transition type between segments
 * CONTINUE: End frame of previous segment becomes start frame (visual continuity)
 * CUT: Fresh start frame generated (scene change, location change, etc.)
 */
export type TransitionType = 'CONTINUE' | 'CUT'

/**
 * Anchor status for the Keyframe State Machine
 * Tracks the progression of frame generation for a segment
 */
export type AnchorStatus = 
  | 'pending'           // No frames generated yet
  | 'start-locked'      // Start frame is ready
  | 'end-pending'       // Start locked, waiting for end frame
  | 'fully-anchored'    // Both start and end frames ready for FTV

/**
 * Action type classification for inverse proportionality weights
 */
export type ActionType = 
  | 'static'           // Character holds pose, no movement
  | 'subtle'           // Micro-expressions, eye movement, breathing
  | 'speaking'         // Dialogue delivery, mouth movement
  | 'gesture'          // Hand gestures, head turns
  | 'movement'         // Walking, repositioning
  | 'action'           // Running, fighting, physical activity
  | 'transformation'   // Major change (costume, lighting, time skip)

/**
 * Segment purpose/type classification for intelligent segment creation
 * Used to apply preset settings and context-aware prompt generation
 */
export type SegmentPurpose = 
  | 'standard'      // Normal scene segment
  | 'extend'        // Extend from previous segment's end frame
  | 'title'         // Title sequence with text overlay
  | 'match-cut'     // Match cut transition between scenes
  | 'establishing'  // Establishing/location shot
  | 'broll'         // B-Roll/visual breather
  | 'outro'         // Outro/credits

/**
 * Frame anchor data for Start/End keyframes
 */
export interface FrameAnchor {
  url: string
  description: string
  generatedAt: string
  actionType?: ActionType
}

// Establishing Shot Types - Video-focused modes for narration backdrops
// DEPRECATED: 'scale-switch' | 'living-painting' | 'b-roll-cutaway' (photo-based tricks)
// NEW: Video generation modes that work with AI video clips
export type EstablishingShotType = 
  | 'single-shot'    // One continuous video for entire narration (loops if needed)
  | 'beat-matched'   // AI splits narration into visual beats, generates multiple segments
  | 'manual-cuts'    // User defines cut points manually
  // Legacy support (deprecated but still valid for existing projects)
  | 'scale-switch' 
  | 'living-painting' 
  | 'b-roll-cutaway' 
  | 'none'

// Beat metadata for beat-matched establishing shots
export interface EstablishingShotBeat {
  beatNumber: number
  startPercent: number
  endPercent: number
  narrationText: string
  visualFocus: string
  shotType: 'wide' | 'medium' | 'close-up' | 'detail' | 'tracking'
  cameraMotion: string
  videoPrompt: string
}

export interface EstablishingShotSettings {
  enabled: boolean
  type: EstablishingShotType
  duration: number // 4-12 seconds
  useExistingFrame: boolean // Use scene's pre-generated frame
  // Beat-matched specific settings
  beats?: EstablishingShotBeat[]
  narrationDuration?: number
}

export type SceneSegmentAssetType = 'video' | 'image' | null

export type GenerationType = 'T2V' | 'I2V' | 'T2I' | 'UPLOAD'

// Veo 3.1 generation methods + CIN for cinematic elements
export type VideoGenerationMethod = 'T2V' | 'I2V' | 'EXT' | 'FTV' | 'REF' | 'CIN'

// ============================================================================
// Unified Generation Config Types
// Shared across all generation dialogs (scene images, keyframes, video clips)
// ============================================================================

/**
 * Type of generation being performed
 */
export type GenerationMode = 'scene-image' | 'keyframe' | 'video-clip' | 'backdrop'

/**
 * Character reference with all data needed for generation
 */
export interface CharacterReference {
  name: string
  referenceImageUrl?: string
  appearance?: string
  ethnicity?: string
  age?: string
  wardrobe?: string
  /** Priority in scene - used when API has reference limits */
  priority?: 'protagonist' | 'speaking' | 'supporting' | 'background'
  /** Whether this character is speaking in the current segment */
  speakingInSegment?: boolean
  /** Dialogue lines for this segment (for voice-sync generation) */
  dialogueLines?: string[]
}

/**
 * Visual reference (scene backdrop or prop/object)
 */
export interface VisualReferenceConfig {
  id: string
  type: 'scene' | 'object'
  name: string
  imageUrl: string
  description?: string
  /** How this reference connects to the prompt */
  promptConnection?: string
}

/**
 * Unified generation configuration used by all dialogs
 * Ensures consistent character reference handling across scene images, keyframes, and video clips
 */
export interface UnifiedGenerationConfig {
  // Generation type
  mode: GenerationMode
  
  // Prompts
  prompt: string
  negativePrompt: string
  
  // Character References (max 5 for images, max 3 for video REF mode)
  characters: CharacterReference[]
  /** Auto-switch to REF mode when character references are critical and I2V would lose them */
  autoSwitchToRefMode?: boolean
  
  // Visual References (scene backdrops, props)
  visualReferences: VisualReferenceConfig[]
  
  // Scene/Visual Setup
  location?: string
  timeOfDay?: string
  weather?: string
  atmosphere?: string
  
  // Camera & Composition
  shotType?: string
  cameraAngle?: string
  cameraMovement?: string
  lensChoice?: string
  
  // Lighting
  lighting?: string
  lightingMood?: string
  
  // Action & Blocking
  characterActions?: string
  talentBlocking?: string
  emotionalBeat?: string
  keyProps?: string
  
  // Style
  artStyle?: string
  
  // Video-specific settings (for video-clip mode)
  videoSettings?: {
    method: VideoGenerationMethod
    duration: 4 | 6 | 8
    aspectRatio: '16:9' | '9:16'
    resolution: '720p' | '1080p'
    startFrameUrl?: string | null
    endFrameUrl?: string | null
    /** For EXT mode - reference to previous Veo video */
    sourceVideoUrl?: string | null
  }
  
  // Keyframe-specific settings
  keyframeSettings?: {
    frameType: 'start' | 'end' | 'both'
    usePreviousEndFrame?: boolean
    previousEndFrameUrl?: string | null
    transitionType?: TransitionType
  }
}

/**
 * Result from character reference prioritization
 * When API limits require selecting subset of characters
 */
export interface CharacterReferencePrioritization {
  /** Characters to include as references (within API limits) */
  included: CharacterReference[]
  /** Characters excluded due to limits */
  excluded: CharacterReference[]
  /** Reason for prioritization choices */
  reason: string
}

// prioritizeCharacterReferences() moved to ./defaults.ts to prevent webpack TDZ errors
// Import from '@/components/vision/scene-production/defaults' instead

// ============================================================================
// Director's Console Types - Pre-Flight Workflow
// ============================================================================

/**
 * Approval status for segment video generation
 * Tracks user review workflow in Director's Console
 */
export type ApprovalStatus = 
  | 'auto-ready'      // System auto-configured, not yet user-reviewed
  | 'user-approved'   // User explicitly reviewed and approved settings
  | 'locked'          // User locked this take - prevents regeneration
  | 'rendering'       // Currently generating video
  | 'rendered'        // Video successfully generated
  | 'error'           // Generation failed

/**
 * Video generation configuration for a segment
 * Auto-drafted by useSegmentConfig hook, editable in DirectorDialog
 */
export interface VideoGenerationConfig {
  // Generation mode/method
  mode: VideoGenerationMethod
  
  // Prompts
  prompt: string              // Active prompt (switches based on mode)
  motionPrompt: string        // Motion-focused prompt for FTV mode
  visualPrompt: string        // Visual-focused prompt for I2V/T2V mode
  negativePrompt: string      // What to avoid in generation
  guidePrompt?: string        // Composed from audio/direction elements (narration, dialogue, music, sfx, direction)
  
  // FTV prompt options
  skipAnchoringPhrase?: boolean  // Skip prepending "IMPORTANT: final frame must match..." for FTV
  
  // Quality tier (FTV defaults to 'premium' for better motion reasoning)
  qualityTier?: 'fast' | 'premium'  // fast: ~$0.20/sec, premium: ~$0.75/sec
  
  // Video parameters
  aspectRatio: '16:9' | '9:16'
  resolution: '720p' | '1080p'
  duration: number            // 4, 6, or 8 seconds
  
  // Asset URLs for generation
  startFrameUrl: string | null
  endFrameUrl: string | null
  sourceVideoUrl: string | null  // For EXT mode
  
  // Reference images for REF mode (up to 3 character/style references)
  referenceImages?: string[]
  
  // Cinematic element settings (for CIN mode)
  cinematicElementType?: string  // Type of cinematic element (title-sequence, match-cut-bridge, etc.)
  
  // Workflow status
  approvalStatus: ApprovalStatus
  confidence: number          // 0-100, auto-calculated confidence in settings
}

/**
 * Queue item for batch video rendering in Director's Console
 */
export interface DirectorQueueItem {
  segmentId: string
  sequenceIndex: number
  config: VideoGenerationConfig
  thumbnailUrl: string | null
  status: 'queued' | 'rendering' | 'complete' | 'error'
  error?: string
  progress?: number           // 0-100 during rendering
}

/**
 * Batch rendering options for Director's Console
 */
export interface BatchRenderOptions {
  mode: 'approved_only' | 'all' | 'selected'
  priority: 'sequence' | 'approved_first'
  delayBetween: number        // ms delay between API calls (rate limiting)
  selectedIds?: string[]      // Segment IDs to render when mode is 'selected'
}

// ============================================================================
// Generation Plan Types - Recommended generation strategy per segment
// ============================================================================

/**
 * Prerequisite status for a generation plan
 */
export interface GenerationPrerequisite {
  type: 'scene-image' | 'previous-frame' | 'character-ref' | 'veo-ref' | 'start-frame' | 'end-frame'
  label: string
  met: boolean
  required: boolean
  assetUrl?: string
}

/**
 * Generation Plan - Recommended strategy for generating a segment
 * Provides guidance for batch automation and user decision-making
 */
export interface GenerationPlan {
  // Primary recommendation
  recommendedMethod: VideoGenerationMethod
  // Confidence in the recommendation (0-100)
  confidence: number
  // Human-readable reasoning
  reasoning: string
  // Fallback if primary method fails or prerequisites not met
  fallbackMethod?: VideoGenerationMethod
  fallbackReason?: string
  // Prerequisites that must be met
  prerequisites: GenerationPrerequisite[]
  // Batch priority (lower = generate first)
  batchPriority: number
  // Estimated quality score if using this plan (0-100)
  qualityEstimate: number
  // Warnings or considerations
  warnings?: string[]
}

/**
 * Prompt context for staleness detection
 * Stores hashes of the source data used to generate the prompt
 */
export interface PromptContext {
  // Hash of dialogue lines covered by this segment
  dialogueHash: string
  // Hash of visual description at generation time
  visualDescriptionHash: string
  // Timestamp when prompt was generated
  generatedAt: string
  // Scene number at generation time
  sceneNumber?: number
  // Script version identifier (if available)
  scriptVersion?: string
}

// ============================================================================
// Audio Anchor Types - For automatic keyframe-to-audio alignment
// ============================================================================

/**
 * Types of audio tracks that keyframes can anchor to
 */
export type AudioAnchorType = 'narration' | 'dialogue' | 'description' | 'sfx' | 'music'

/**
 * Position within an audio clip to anchor to
 */
export type AudioAnchorPosition = 'start' | 'end'

/**
 * Audio anchor configuration for automatic keyframe timing
 * When set, the segment's display timing in Screening Room is automatically
 * calculated based on the referenced audio clip's position and duration.
 */
export interface AudioAnchor {
  // Type of audio track to anchor to
  type: AudioAnchorType
  // For dialogue: which character's audio clip (by index or character name)
  trackIndex?: number
  characterName?: string
  // Whether to align to start or end of the audio clip
  position: AudioAnchorPosition
  // Optional offset from anchor point (positive = after, negative = before)
  offsetSeconds?: number
}

/**
 * Duration calculation mode for anchored segments
 * - 'manual': Use imageDuration value directly
 * - 'fill-to-next': Extend to next segment's anchor or end of scene
 * - 'match-audio': Match the anchored audio clip's duration
 * - 'split-even': Split duration evenly with sibling segments on same audio
 */
export type DurationMode = 'manual' | 'fill-to-next' | 'match-audio' | 'split-even'

export interface SceneSegmentTake {
  id: string
  createdAt: string
  assetUrl: string
  thumbnailUrl?: string
  durationSec?: number
  status: SceneSegmentStatus
  notes?: string
  // Video URL - the actual playable video asset (may differ from assetUrl for blob storage)
  videoUrl?: string
  // Last frame URL - extracted from the actual video for I2V extension continuity
  // This is the REAL last frame from the video, not a pre-generated keyframe
  lastFrameUrl?: string
  // Veo video reference for extension - stores the Gemini Files API reference (e.g., "files/xxx")
  // This is needed for Veo video extension which only works with Veo-generated videos still in Gemini's system
  veoVideoRef?: string
  // ISO timestamp when veoVideoRef expires (48 hours from generation)
  // After this time, video extension falls back to I2V mode with the last frame
  veoVideoRefExpiry?: string
}

export interface SceneSegmentReferences {
  startFrameUrl?: string | null
  endFrameUrl?: string | null
  // Enhanced reference data
  useSceneFrame?: boolean
  characterRefs?: string[] // Character names to use as references
  startFrameDescription?: string | null
  endFrameDescription?: string | null
  characterIds: string[]
  sceneRefIds: string[]
  objectRefIds: string[]
  
  // Keyframe State Machine - Frame Anchors
  startFrameAnchor?: FrameAnchor | null
  endFrameAnchor?: FrameAnchor | null
}

export interface SceneSegment {
  segmentId: string
  sequenceIndex: number
  startTime: number
  endTime: number
  status: SceneSegmentStatus
  generatedPrompt?: string
  userEditedPrompt?: string | null
  activeAssetUrl?: string | null
  assetType: SceneSegmentAssetType
  references: SceneSegmentReferences
  takes: SceneSegmentTake[]
  // Shot Metadata
  shotType?: string
  cameraAngle?: string
  cameraMovement?: string
  subject?: string
  action?: string
  transition?: 'cut' | 'dissolve' | 'fade_out'
  trigger?: string
  visualFrame?: string // e.g. "Shot Frame" url if separate from activeAssetUrl
  // Enhanced Veo 3.1 metadata
  generationMethod?: VideoGenerationMethod
  triggerReason?: string // Why we cut here (speaker change, action change, etc.)
  endFrameDescription?: string // Lookahead for next segment
  emotionalBeat?: string // The emotional intent of this segment
  // Phase 1: Character and Dialogue mapping for scene coverage
  characters?: SegmentCharacter[]  // Characters present in this segment
  dialogueLines?: SegmentDialogueLine[]  // Dialogue lines assigned to this segment
  dialogueLineIds?: string[]  // Phase 6: IDs of assigned dialogue lines (persisted to DB)
  // Phase 3: Keyframe settings for Ken Burns animation
  keyframeSettings?: SegmentKeyframeSettings
  // Establishing Shot metadata
  isEstablishingShot?: boolean
  establishingShotType?: EstablishingShotType
  shotNumber?: number // For B-Roll multi-shot sequences (1, 2, etc.)
  // Generation Plan - recommended strategy for batch automation
  generationPlan?: GenerationPlan
  // Prompt Context - for staleness detection when script changes
  promptContext?: PromptContext
  // Staleness flag - set when script changes invalidate the prompt
  isStale?: boolean
  // User instruction - general text instruction that overrides/augments prompts
  userInstruction?: string
  // Error message - stored when generation fails for detailed display
  errorMessage?: string
  
  // Segment Direction - approved direction metadata from the AI segmentation phase
  // Contains characters, isNoTalent, shotType, etc. from the user-approved direction
  segmentDirection?: SegmentDirection | null
  
  // ============================================================================
  // Keyframe State Machine Fields
  // ============================================================================
  
  // Transition type: CONTINUE (inherit from previous) or CUT (fresh frame)
  transitionType?: TransitionType
  
  // Anchor status: tracks frame generation workflow state
  anchorStatus?: AnchorStatus
  
  // Action type: classified action for inverse proportionality weights
  actionType?: ActionType
  
  // Action prompt: describes what happens during this segment (for AI generation)
  actionPrompt?: string
  
  // ============================================================================
  // Pasted/AI-Generated Frame Prompts (from Copy Prompt/Paste Results workflow)
  // ============================================================================
  
  // Start frame generation prompt (from pasted AI segmentation results)
  startFramePrompt?: string
  
  // End frame generation prompt (from pasted AI segmentation results)
  endFramePrompt?: string
  
  // Video generation prompt describing motion between start/end frames
  videoPrompt?: string
  
  // Start frame URL (convenience accessor, also in references.startFrameUrl)
  startFrameUrl?: string | null
  
  // End frame URL (convenience accessor, also in references.endFrameUrl)
  endFrameUrl?: string | null
  
  // Production lock - prevents regeneration in Director's Console
  // Persisted to DB, survives page reloads
  lockedForProduction?: boolean
  
  // ============================================================================
  // Screening Room Animatic Settings
  // ============================================================================
  
  // Total image display duration for Screening Room player (in seconds)
  // Controls how long this segment's frame(s) display in the animatic
  // Default: (endTime - startTime) * 2
  imageDuration?: number
  
  // ============================================================================
  // Audio Anchor Settings (for Screening Room timing alignment)
  // ============================================================================
  
  // Audio anchor - automatically calculates display startTime from audio position
  // When set, the segment's keyframe display timing syncs to the referenced audio clip
  audioAnchor?: AudioAnchor
  
  // Duration mode - how to calculate display duration when anchored
  // 'manual' = use imageDuration value
  // 'fill-to-next' = extend to next segment's anchor or end of scene
  // 'match-audio' = match the anchored audio clip's duration
  // 'split-even' = split duration evenly with sibling segments on same audio
  durationMode?: DurationMode
  
  // ============================================================================
  // Segment Purpose/Type (for intelligent segment creation)
  // ============================================================================
  
  // Segment purpose classification for preset settings
  segmentPurpose?: SegmentPurpose
  
  // Special segment flag - true for cinematic elements (title, match-cut, establishing, b-roll, outro)
  // Special segments are video-only placeholders that don't require keyframe images
  isSpecialSegment?: boolean
  
  // ============================================================================
  // Uploaded Video Duration (for user-uploaded videos that may exceed 8s limit)
  // ============================================================================
  
  // Actual video duration in seconds (extracted from uploaded video metadata)
  // Used to override startTime/endTime for uploaded videos that exceed AI-generated limits
  actualVideoDuration?: number
  
  // Flag indicating this segment contains a user-uploaded video (vs AI-generated)
  isUserUpload?: boolean

  // ===========================================================================
  // Lean Multi-Language (LML) Elastic Segment Fields
  // ===========================================================================
  
  // LML extension mode for this segment (calculated, not persisted)
  lmlMode?: SegmentDynamicsMode
  
  // Freeze-frame extension duration in seconds (calculated)
  freezeExtension?: number
  
  // Audio overrun amount in seconds (how much audio exceeds video)
  audioOverrun?: number
}

// Character presence in a segment
export interface SegmentCharacter {
  name: string
  role: 'speaking' | 'present' | 'background'
}

// Dialogue line assigned to a segment
export interface SegmentDialogueLine {
  id: string
  character: string
  line: string
  covered: boolean  // User confirms this dialogue is covered by the segment
}

// Ken Burns keyframe settings for manual animation control
export type KeyframeEasingType = 'smooth' | 'drift' | 'push' | 'dramatic'
export type KeyframePanDirection = 'none' | 'left' | 'right' | 'up' | 'down' | 'up-left' | 'up-right' | 'down-left' | 'down-right'

export interface SegmentKeyframeSettings {
  // Zoom keyframes (1.0 = no zoom, 1.2 = 20% zoom in)
  zoomStart: number  // 0.8 - 1.5
  zoomEnd: number    // 0.8 - 1.5
  // Pan keyframes (percentage offset from center, -50 to 50)
  panStartX: number
  panStartY: number
  panEndX: number
  panEndY: number
  // Easing for the transition
  easingType: KeyframeEasingType
  // Preset direction (overrides individual pan values)
  direction?: KeyframePanDirection
  // Whether to use auto-detected values or manual settings
  useAutoDetect: boolean
}

// ============================================================================
// Production Stream Types - Multi-Language Video Production
// ============================================================================

/**
 * Audio mix configuration for a production stream
 * Stores the timing and volume settings used during render
 */
export interface ProductionAudioMixConfig {
  narration: { enabled: boolean; volume: number; startOffset: number }
  dialogue: { enabled: boolean; volume: number; startOffset: number }
  music: { enabled: boolean; volume: number; startOffset: number }
  sfx: { enabled: boolean; volume: number; startOffset: number }
  segmentAudio: { enabled: boolean; volume: number }
}

/**
 * Production stream status
 */
export type ProductionStreamStatus = 'pending' | 'rendering' | 'complete' | 'failed' | 'stale' | 'outdated'

/**
 * Stream type - animatic (Ken Burns keyframes) vs video (AI-generated video)
 */
export type ProductionStreamType = 'animatic' | 'video'

/** Unified mixer / export target: output kind + language for audio and preview policy */
export interface ProductionTarget {
  streamType: ProductionStreamType
  language: string
}

/**
 * Ken Burns intensity for animatic rendering
 */
export type KenBurnsIntensity = 'off' | 'subtle' | 'medium' | 'dramatic'

/**
 * Transition style between keyframes
 */
export type TransitionStyle = 'cut' | 'crossfade' | 'fade-to-black'

/**
 * Render settings specific to animatic streams
 */
export interface AnimaticRenderSettings {
  type: 'animatic'
  /** Ken Burns pan/zoom intensity */
  kenBurnsIntensity: KenBurnsIntensity
  /** Transition style between keyframes */
  transitionStyle: TransitionStyle
  /** Transition duration in seconds (for crossfade/fade-to-black) */
  transitionDuration: number
  /** Whether to burn in subtitles */
  includeSubtitles: boolean
  /** Subtitle styling (if includeSubtitles is true) */
  subtitleStyle?: SubtitleStyle
}

/**
 * Render settings specific to video streams
 */
export interface VideoRenderSettings {
  type: 'video'
  /** Whether to upscale to higher resolution */
  upscale: boolean
  /** Upscale model to use */
  upscaleModel?: 'standard' | 'cinematic'
  /** Motion intensity for AI video generation */
  motionIntensity: 'low' | 'medium' | 'high'
  /** Whether to burn in subtitles */
  includeSubtitles: boolean
  /** Subtitle styling (if includeSubtitles is true) */
  subtitleStyle?: SubtitleStyle
}

/**
 * Subtitle style configuration for burned-in subtitles
 */
export interface SubtitleStyle {
  fontFamily: string
  fontSize: number
  color: string
  backgroundColor: string
  position: 'bottom' | 'top'
}

/**
 * Discriminated union of render settings
 */
export type ProductionRenderSettings = AnimaticRenderSettings | VideoRenderSettings

/**
 * A rendered production stream for a specific language and type
 * Enables multiple language versions AND animatic vs video versions of the same scene
 */
export interface ProductionStream {
  /** Unique identifier for this production stream */
  id: string
  /** Stream type: animatic (Ken Burns) or video (AI-generated) */
  streamType: ProductionStreamType
  /** Language code (e.g., 'en', 'th', 'es') */
  language: string
  /** Human-readable language name (e.g., 'English', 'Thai', 'Spanish') */
  languageLabel: string
  /** URL of the rendered MP4 video (null until render completes) */
  mp4Url?: string | null
  /** File size in bytes */
  fileSize?: number
  /** Audio mix configuration used for this render */
  audioMixConfig?: ProductionAudioMixConfig
  /** Render settings used (animatic or video specific) */
  renderSettings?: ProductionRenderSettings
  /** Resolution of the rendered video */
  resolution?: '720p' | '1080p' | '4K'
  /** ISO timestamp when stream was created */
  createdAt?: string
  /** ISO timestamp when rendering started */
  startedAt?: string
  /** ISO timestamp when rendering completed */
  completedAt?: string
  /** Total duration in seconds */
  duration?: number
  /** Current status of the production stream */
  status: ProductionStreamStatus
  /** Hash of segments + audio for staleness detection */
  sourceHash?: string
  /** Error message if status is 'failed' */
  error?: string
  /** Render job ID for tracking */
  renderJobId?: string
}

// isAnimaticStream(), isVideoStream(), DEFAULT_ANIMATIC_SETTINGS, DEFAULT_VIDEO_SETTINGS
// moved to ./defaults.ts to prevent webpack TDZ errors
// Import from '@/components/vision/scene-production/defaults' instead

// ============================================================================
// Timeline Audio (V1) Types - Used by Screening Room + Scene Timeline
// ============================================================================

export interface AudioTrackClip {
  id: string
  url?: string | null
  startTime: number
  duration: number
  label?: string
  volume?: number
  trimStart?: number
  trimEnd?: number
}

export interface AudioTracksData {
  voiceover?: AudioTrackClip | null
  narration?: AudioTrackClip | null
  dialogue?: AudioTrackClip[]
  music?: AudioTrackClip | null
  sfx?: AudioTrackClip[]
}

export interface SceneProductionData {
  isSegmented: boolean
  targetSegmentDuration: number
  segments: SceneSegment[]
  lastGeneratedAt?: string | null
  /** Optional timeline audio clips for this scene */
  audioTracks?: AudioTracksData
  /** Text overlays for this scene (titles, lower-thirds, subtitles) */
  textOverlays?: TextOverlayData[]
  /** @deprecated Use productionStreams instead. Kept for backwards compatibility. */
  renderedSceneUrl?: string | null
  /** @deprecated Use productionStreams instead. Kept for backwards compatibility. */
  renderedAt?: string | null
  /** Multi-language production streams */
  productionStreams?: ProductionStream[]
}

/**
 * Text overlay data stored in production data
 * Simplified version for persistence (full types in SceneProductionMixer.tsx)
 */
export interface TextOverlayData {
  id: string
  text: string
  subtext?: string
  position: {
    x: number
    y: number
    anchor: 'top-left' | 'top-center' | 'center' | 'bottom-left' | 'bottom-center' | 'bottom-right'
  }
  style: {
    preset: 'title' | 'lower-third' | 'subtitle' | 'custom'
    fontFamily: string
    fontSize: number
    fontWeight: 400 | 500 | 600 | 700 | 800
    color: string
    backgroundColor?: string
    backgroundOpacity?: number
    textShadow?: boolean
    padding?: number
  }
  timing: {
    startTime: number
    duration: number
    fadeInMs: number
    fadeOutMs: number
  }
  animation?: {
    enter: 'fade' | 'slide-up' | 'slide-left' | 'typewriter' | 'none'
    exit: 'fade' | 'slide-down' | 'slide-right' | 'none'
  }
}

export interface SceneProductionReferences {
  characters: any[]
  sceneReferences: VisualReference[]
  objectReferences: VisualReference[]
}

// ============================================================================
// V2 Audio Timeline Types - Multi-Language Support & Single Source of Truth
// ============================================================================

/**
 * Supported audio track types in the timeline
 */
export type AudioTrackType = 'voiceover' | 'description' | 'dialogue' | 'music' | 'sfx'

/**
 * Source of an audio clip - used for debugging and cleanup
 */
export type AudioClipSource = 'scene' | 'upload' | 'generated'

/**
 * Base audio clip definition (extends V1 AudioTrackClip for compatibility)
 */
export interface AudioTrackClipV2 {
  id: string
  url: string | null  // null = no audio, avoids stale URL references
  startTime: number   // In seconds, relative to scene start
  duration: number    // In seconds
  label?: string
  volume?: number     // 0-1
  trimStart?: number  // Offset from start of source
  trimEnd?: number    // Offset from end of source
  // V2 additions
  language: string    // 'en', 'es', 'th', etc.
  source: AudioClipSource
  scenePropertyPath?: string  // e.g., 'narrationAudio.en.url' for debugging
  characterName?: string      // For dialogue clips
  dialogueIndex?: number      // Index in scene.dialogue array
  // Stale audio warning
  isStale?: boolean           // True if audio doesn't match current dialogue
  staleReason?: string        // Human-readable reason for stale status
  // Smart segment-aligned timing (for multi-language support)
  actualDuration?: number     // Actual audio duration (may differ from timeline duration)
  baselineDuration?: number   // Duration in baseline language (for delta calculation)
  durationDelta?: number      // Difference: actualDuration - baselineDuration
}

/**
 * Multi-language audio tracks - stores all languages, keyed by language code
 */
export interface MultiLanguageAudioTracks {
  [language: string]: AudioTracksDataV2
}

/**
 * Audio tracks for a single language
 */
export interface AudioTracksDataV2 {
  voiceover: AudioTrackClipV2 | null
  description: AudioTrackClipV2 | null
  dialogue: AudioTrackClipV2[]
  music: AudioTrackClipV2 | null
  sfx: AudioTrackClipV2[]
}

/**
 * Complete timeline audio state - tracks selected language and available options
 */
export interface TimelineAudioState {
  selectedLanguage: string
  availableLanguages: string[]
  tracks: MultiLanguageAudioTracks
  audioHash: string  // Hash of all URLs for change detection
}

/**
 * Props for SceneTimelineV2 component
 */
export interface SceneTimelineV2Props {
  /**
   * Mode determines player behavior:
   * - 'storyboard': Only shows keyframes (start/end frames), never video. Includes Ken Burns animation.
   * - 'video': Shows video if available, falls back to keyframes. Default mode.
   */
  mode?: 'storyboard' | 'video'
  segments: SceneSegment[]
  scene: any  // Scene object from script.script.scenes[idx]
  selectedSegmentId?: string
  selectedLanguage: string
  onLanguageChange: (language: string) => void
  onSegmentSelect: (segmentId: string) => void
  onPlayheadChange?: (time: number, segmentId?: string) => void
  onGenerateSceneMp4?: () => void
  onVisualClipChange?: (clipId: string, changes: { startTime?: number; duration?: number; trimStart?: number; trimEnd?: number }) => void
  onAudioClipChange?: (trackType: AudioTrackType, clipId: string, changes: { startTime?: number; duration?: number }) => void
  onAddSegment?: (afterSegmentId: string | null, duration: number) => void
  onDeleteSegment?: (segmentId: string) => void
  onReorderSegments?: (oldIndex: number, newIndex: number) => void
  onAddEstablishingShot?: () => void
  onAudioError?: (clipId: string, url: string) => void  // Handle 404s
  sceneFrameUrl?: string | null
  // Phase 2: Dialogue coverage indicators
  dialogueAssignments?: Record<string, Set<string>>
  // Phase 8: Audio alignment features
  onSegmentTimeChange?: (segmentId: string, newStartTime: number, newEndTime: number) => void
  onFitSegmentToDialogue?: (segmentId: string) => void
  onOpenSegmentPromptDialog?: (segmentId: string) => void
  // Phase 9: Intelligent audio anchoring
  onApplyIntelligentAlignment?: () => void
  // Phase 10: Language playback offset for translated audio
  playbackOffset?: number  // Per-segment offset in seconds for current language
  suggestedOffset?: number // Auto-calculated suggested offset based on audio delta
  onPlaybackOffsetChange?: (offset: number) => void  // Save offset for current language
}

// ============================================================================
// Smart Prompt Video Editing Types - Constraint-Based UI for Veo 3.1
// ============================================================================

/**
 * Camera movement types supported by Veo 3.1
 */
export type CameraMovementType = 
  | 'static'
  | 'dolly-in'
  | 'pull-out'
  | 'pan-left'
  | 'pan-right'
  | 'tilt-up'
  | 'tilt-down'
  | 'crane'
  | 'handheld'
  | 'steadicam'
  | 'track'
  | 'orbit'
  | 'whip-pan'

/**
 * Shot framing types
 */
export type ShotFramingType =
  | 'extreme-wide'
  | 'wide'
  | 'medium-wide'
  | 'medium'
  | 'medium-close'
  | 'close-up'
  | 'extreme-close-up'
  | 'over-shoulder'
  | 'two-shot'
  | 'insert'

/**
 * Camera movement velocity
 */
export type CameraVelocity = 'slow' | 'medium' | 'fast'

/**
 * Focus behavior for camera
 */
export type FocusMode = 'locked' | 'rack' | 'follow' | 'deep'

/**
 * Camera & Temporal Control Settings
 * Module 1: Controls camera movement, framing, and temporal aspects
 */
export interface CameraControlSettings {
  // Movement
  movementType: CameraMovementType
  velocity: CameraVelocity
  // Framing
  shotFraming: ShotFramingType
  // Focus
  focusMode: FocusMode
  focusTarget?: string  // Character name or "subject"
  // Duration override (if different from segment duration)
  durationOverride?: number
  // Temporal controls
  motionIntensity: number  // 0-100, how much action/movement
  pacingStyle: 'contemplative' | 'natural' | 'dynamic' | 'frenetic'
}

/**
 * Lip-sync priority for performance
 */
export type LipSyncPriority = 'off' | 'loose' | 'tight'

/**
 * Eye contact behavior
 */
export type EyeContactMode = 'natural' | 'camera-aware' | 'avoid' | 'scene-specific'

/**
 * Performance & Dialog Sync Settings
 * Module 2: Controls actor performance and dialogue synchronization
 */
export interface PerformanceSettings {
  // Lip-sync (Phase 1 - Coming Soon placeholder)
  lipSyncEnabled: boolean
  lipSyncPriority: LipSyncPriority
  // Expression intensity (how much facial expression change)
  expressionIntensity: number  // 0-100
  // Micro-expressions toggle
  microExpressionsEnabled: boolean
  // Eye contact behavior
  eyeContactMode: EyeContactMode
  // Character focus (which character is primary in this segment)
  primaryCharacter?: string
  // Emotional state override
  emotionalState?: string  // "calm", "tense", "joyful", etc.
  // Body language intensity
  bodyLanguageIntensity: number  // 0-100
}

/**
 * Visual style presets
 */
export type VisualStylePreset = 
  | 'cinematic'
  | 'documentary'
  | 'commercial'
  | 'music-video'
  | 'horror'
  | 'romantic'
  | 'noir'
  | 'vintage'
  | 'custom'

/**
 * Lighting style
 */
export type LightingStyle = 
  | 'natural'
  | 'studio'
  | 'dramatic'
  | 'soft'
  | 'high-key'
  | 'low-key'
  | 'golden-hour'
  | 'blue-hour'
  | 'neon'
  | 'practical'

/**
 * Color grading preset
 */
export type ColorGradingPreset =
  | 'neutral'
  | 'warm'
  | 'cool'
  | 'teal-orange'
  | 'bleach-bypass'
  | 'vintage'
  | 'high-contrast'
  | 'desaturated'
  | 'vibrant'

/**
 * Visual Style Settings
 * Module 3: Controls look and feel of the generated video
 */
export interface VisualStyleSettings {
  // Style preset (quick selection)
  stylePreset: VisualStylePreset
  // Lighting
  lighting: LightingStyle
  lightingIntensity: number  // 0-100
  // Color grading
  colorGrading: ColorGradingPreset
  saturation: number  // 0-100, 50 = neutral
  contrast: number    // 0-100, 50 = neutral
  // Film grain / texture
  filmGrainEnabled: boolean
  filmGrainIntensity: number  // 0-100
  // Depth of field
  depthOfFieldEnabled: boolean
  apertureStyle: 'wide' | 'normal' | 'shallow'
  // Atmosphere
  atmosphereType?: 'none' | 'haze' | 'fog' | 'rain' | 'snow' | 'dust'
  atmosphereIntensity?: number  // 0-100
}

/**
 * Magic Edit selection method
 */
export type MagicEditSelectionMethod = 'auto' | 'mask' | 'prompt'

/**
 * Magic Edit operation type
 */
export type MagicEditOperationType = 
  | 'replace'      // Replace object with something else
  | 'remove'       // Remove object from scene
  | 'add'          // Add object to scene
  | 'modify'       // Modify existing object
  | 'style-transfer'  // Apply style to selection

/**
 * Magic Edit Settings (In-Painting / Object Manipulation)
 * Module 4: Targeted edits to specific regions or objects
 */
export interface MagicEditSettings {
  // Whether magic edit is enabled for this generation
  enabled: boolean
  // How the target is selected
  selectionMethod: MagicEditSelectionMethod
  // What to do with the selection
  operationType: MagicEditOperationType
  // The target description (what to select)
  targetDescription: string
  // What to do with the target
  changeDescription: string
  // Face preservation (important for character consistency)
  preserveFaces: boolean
  // Mask image URL (if using mask-based selection)
  maskUrl?: string
  // Blend mode for the edit
  blendStrength: number  // 0-100, how much the edit blends with original
}

/**
 * Combined settings for all Smart Prompt modules
 */
export interface SmartPromptSettings {
  camera: CameraControlSettings
  performance: PerformanceSettings
  visualStyle: VisualStyleSettings
  magicEdit: MagicEditSettings
}

// createDefaultSmartPromptSettings() moved to ./defaults.ts to prevent webpack TDZ errors
// Import from '@/components/vision/scene-production/defaults' instead

/**
 * Video Prompt Payload - Final output to Veo 3.1 API
 * This is what the prompt compiler produces from SmartPromptSettings
 */
export interface VideoPromptPayload {
  // Core prompt text (compiled from all settings)
  basePrompt: string
  // Negative prompt (things to avoid)
  negativePrompt: string
  // Generation method
  method: VideoGenerationMethod
  // Duration in seconds
  durationSeconds: number
  // Aspect ratio
  aspectRatio: '16:9' | '9:16' | '1:1'
  // Reference frames
  startFrameUrl?: string
  endFrameUrl?: string
  // Reference images (character/scene refs)
  referenceImages?: string[]
  // Video extension source
  sourceVideoRef?: string  // Veo video reference for extension
  // Control signals derived from SmartPromptSettings
  controlSignals: {
    cameraMovement: string
    cameraVelocity: string
    shotFraming: string
    motionIntensity: number
    lightingStyle: string
    colorGrading: string
    atmosphereType?: string
  }
  // Audio guidance (for lip-sync and dialog sync)
  audioGuidance?: {
    audioUrl?: string
    lipSyncEnabled: boolean
    syncPriority: LipSyncPriority
  }
  // Temporal consistency hints
  temporalConsistency: {
    preserveCharacters: string[]  // Character names to preserve
    preserveEnvironment: boolean
    previousSegmentUrl?: string   // For continuity
  }
  // Magic edit payload (if enabled)
  magicEditPayload?: {
    targetMask?: string
    targetPrompt: string
    changePrompt: string
    preserveFaces: boolean
    blendStrength: number
  }
}

// ============================================================================
// Voice Anchor Types - For Veo 3.1 consistent voice synthesis
// ============================================================================

/**
 * Narrator voice type presets for consistent voiceover generation
 * Used in Veo 3.1 prompts to describe the voice that should speak narration
 */
export type NarratorVoiceType = 
  | 'deep-masculine'       // Deep, authoritative male voice
  | 'warm-feminine'        // Warm, expressive female voice
  | 'neutral-documentary'  // Professional, neutral documentary style
  | 'elderly-wise'         // Aged, contemplative voice
  | 'young-energetic'      // Youthful, dynamic voice
  | 'custom'               // User-defined custom description

/**
 * Voice anchor for consistent voice generation in Veo 3.1
 * Based on the "Voice Anchor" concept from Veo prompt optimization guide
 */
export interface VoiceAnchor {
  type: NarratorVoiceType
  /** Custom description when type is 'custom' */
  customDescription?: string
  /** Additional voice modifiers (e.g., "British accent", "whispering") */
  modifiers?: string[]
}

/**
 * Voice anchor preset with display info and prompt text
 */
export interface VoiceAnchorPreset {
  type: NarratorVoiceType
  label: string
  description: string
  /** The actual text to include in Veo prompts */
  promptText: string
}

/**
 * Audio track timing settings for timeline controls
 */
export interface AudioTrackTimingSettings {
  startTime: number  // In seconds, relative to scene start
  duration: number   // In seconds
}

/**
 * Audio track selection for video playback overlay
 */
export interface SelectedAudioTracks {
  narration: boolean
  dialogue: boolean
  music: boolean
  sfx: boolean
}

/**
 * Extended audio track selection with timing settings
 */
export interface AudioTrackSelectionWithTiming {
  narration: { enabled: boolean; timing: AudioTrackTimingSettings }
  dialogue: { enabled: boolean; timing: AudioTrackTimingSettings }
  music: { enabled: boolean; timing: AudioTrackTimingSettings }
  sfx: { enabled: boolean; timing: AudioTrackTimingSettings }
}

/**
 * Audio track data for playback
 */
export interface AudioTrackData {
  type: 'narration' | 'dialogue' | 'music' | 'sfx'
  audioUrl?: string
  label: string
  enabled: boolean
}

/**
 * Audio clip configuration for timeline-based playback
 * Supports start time, duration, and volume for precise audio-video alignment
 */
export interface AudioClipConfig {
  url: string
  startTime: number    // In seconds, relative to scene start
  duration: number     // In seconds
  volume: number       // 0-1
  loop?: boolean       // Whether to loop the audio
}

/**
 * Complete audio configuration for scene playback with timeline settings
 */
export interface SceneAudioConfig {
  narration?: AudioClipConfig
  music?: AudioClipConfig
  dialogue?: AudioClipConfig[]
  sfx?: AudioClipConfig[]
}

/**
 * Volume settings per track type
 */
export interface AudioVolumes {
  narration: number
  dialogue: number
  music: number
  sfx: number
}

// ============================================================================
// Mixer Timeline Types (moved from SceneProductionMixer to break circular dep)
// ============================================================================

/**
 * Text overlay style configuration
 */
export interface TextOverlayStyle {
  preset: 'title' | 'lower-third' | 'subtitle' | 'custom'
  fontFamily: string
  fontSize: number  // percentage of video height (e.g., 8 = 8%)
  fontWeight: 400 | 500 | 600 | 700 | 800
  color: string
  backgroundColor?: string
  backgroundOpacity?: number
  textShadow?: boolean
  padding?: number
}

/**
 * Text overlay position
 */
export interface TextOverlayPosition {
  x: number  // 0-100 percentage
  y: number  // 0-100 percentage
  anchor: 'top-left' | 'top-center' | 'center' | 'bottom-left' | 'bottom-center' | 'bottom-right'
}

/**
 * Text overlay timing
 */
export interface TextOverlayTiming {
  startTime: number   // seconds from video start
  duration: number    // seconds, or -1 for full video
  fadeInMs: number
  fadeOutMs: number
}

/**
 * Text overlay configuration for video captions, titles, and lower thirds
 */
export interface TextOverlay {
  id: string
  text: string
  subtext?: string  // For lower thirds (name + title)
  position: TextOverlayPosition
  style: TextOverlayStyle
  timing: TextOverlayTiming
  animation?: {
    enter: 'fade' | 'slide-up' | 'slide-left' | 'typewriter' | 'none'
    exit: 'fade' | 'slide-down' | 'slide-right' | 'none'
  }
}

/**
 * Audio track configuration for mixer
 */
export interface AudioTrackConfig {
  enabled: boolean
  volume: number       // 0 to 1
  startOffset: number  // Legacy: Start time in seconds
  startSegment: number // Segment index where audio starts (0-based)
  endSegment: number   // Segment index where audio ends (0-based, -1 = all remaining)
  duration?: number    // Optional duration override (for music)
}

/**
 * Audio tracks for the scene mixer
 */
export interface MixerAudioTracks {
  narration: AudioTrackConfig
  dialogue: AudioTrackConfig
  music: AudioTrackConfig
  sfx: AudioTrackConfig
}

// ============================================================================
// Segment Builder Types (moved here to break circular dependency)
// These types were previously in SegmentBuilder.tsx, causing circular imports
// with SegmentValidation.ts, SegmentPreviewTimeline.tsx, SegmentPromptEditor.tsx
// ============================================================================

/**
 * Validation rule severity
 */
export type ValidationSeverity = 'error' | 'warning' | 'info'

/**
 * Individual validation issue
 */
export interface ValidationIssue {
  code: string
  severity: ValidationSeverity
  message: string
  field?: string
  suggestion?: string
}

/**
 * Complete validation result for a segment
 */
export interface ValidationResult {
  isValid: boolean
  issues: ValidationIssue[]
  // Computed scores
  durationScore: number      // 0-100, how well duration fits constraints
  bibleFidelityScore: number // 0-100, how well prompt matches scene bible
  promptQualityScore: number // 0-100, overall prompt effectiveness
}

/**
 * Scene Bible - Immutable scene content during segmentation
 * This is the "single source of truth" for the scene's creative content
 */
export interface SceneBible {
  sceneId: string
  sceneNumber: number
  heading: string
  location: string
  timeOfDay: string
  visualDescription: string
  narration: string | null
  dialogue: Array<{
    id: string
    character: string
    text: string
    emotion?: string
  }>
  characters: Array<{
    id: string
    name: string
    description?: string
    appearanceDescription?: string
    referenceImageUrl?: string
  }>
  sceneFrameUrl?: string | null
  // Computed content hash for staleness detection
  contentHash: string
}

/**
 * Segment direction from Phase 1 (user reviews before prompt generation)
 */
export interface ProposedDirection {
  id: string
  sequenceIndex: number
  estimatedDuration: number
  shotType: string
  talentAction: string
  dialogueLineIds: string[]
  generationMethod: 'T2V' | 'I2V' | 'EXT' | 'FTV'
  triggerReason: string
  
  // Phase 8: Keyframe specific fields for prompt enrichment
  /** Detailed keyframe start frame description for Imagen generation */
  keyframeStartDescription?: string
  /** Detailed keyframe end frame description for Imagen generation */
  keyframeEndDescription?: string
  
  // User review status
  isApproved: boolean
  isUserEdited: boolean
}

/**
 * Proposed segment from AI analysis (preview mode) - Phase 2 output
 */
export interface ProposedSegment {
  id: string
  sequenceIndex: number
  startTime: number
  endTime: number
  duration: number
  triggerReason: string
  generationMethod: 'T2V' | 'I2V' | 'EXT' | 'FTV'
  generatedPrompt: string
  emotionalBeat: string
  dialogueLineIds: string[]
  confidence: number
  // Validation status
  validation?: ValidationResult
  // User adjustments
  isAdjusted: boolean
  userEditedPrompt?: string | null
  // Link to approved direction
  directionId?: string
}

/**
 * Workflow phase for the builder
 */
export type BuilderPhase = 'analyze'

// ============================================================================
// Lean Multi-Language (LML) Elastic Segment Types
// ============================================================================

/**
 * LML extension mode for a segment
 * - EXACT: Audio ≤ video duration — no visual extension needed
 * - SMART_PAD: Audio overruns by ≤ threshold — minor visual hold, no Ken Burns
 * - FREEZE_EXTEND: Audio overruns by > threshold — freeze last frame + Ken Burns micro-zoom
 */
export type SegmentDynamicsMode = 'EXACT' | 'SMART_PAD' | 'FREEZE_EXTEND'

/**
 * Ken Burns visual effect configuration for freeze-frame extension
 */
export interface LMLVisualEffect {
  type: 'none' | 'kenburns'
  /** Scale range: [startScale, endScale] — e.g. [1.0, 1.01] for micro-zoom */
  scale: [number, number]
  /** Duration of the visual effect in seconds */
  duration: number
}

/**
 * Result of calculateSegmentDynamics() — the core LML decision per segment
 */
export interface SegmentDynamicsResult {
  /** Segment index in the production */
  segmentIndex: number
  /** Which extension mode applies */
  mode: SegmentDynamicsMode
  /** Seconds of visual extension needed (0 for EXACT) */
  extension: number
  /** Cumulative offset for downstream segments (sum of all previous extensions) */
  cumulativeOffset: number
  /** Visual effect to apply during the extension period */
  visualEffect: LMLVisualEffect
  /** Base video duration (from segment endTime - startTime) */
  baseDuration: number
  /** Effective display duration (baseDuration + extension) */
  displayDuration: number
  /** Audio overrun amount (negative = audio shorter than video) */
  audioOverrun: number
  /** 50ms gain ramp-down flag for clean anchor transitions */
  applyGainRampDown: boolean
}

/**
 * LML configuration constants — tunable thresholds
 * Exposed as constants so they can be overridden per-production in the future
 */
export interface LMLConfig {
  /** Threshold in seconds: overruns ≤ this are SMART_PAD, > are FREEZE_EXTEND */
  smartPadThreshold: number
  /** Ken Burns micro-zoom end scale (start is always 1.0) */
  kenBurnsEndScale: number
  /** Gain ramp-down duration in seconds at segment transitions */
  gainRampDownDuration: number
  /** Maximum allowed extension per segment (safety cap) */
  maxExtensionPerSegment: number
}

/**
 * Sync status for a segment — used by the Sync-Status Bar UI
 */
export type SegmentSyncStatus = 'base' | 'smart-pad' | 'freeze-extend'

/**
 * Complete LML timing analysis for an entire scene across a language
 */
export interface SceneLMLAnalysis {
  /** Language code this analysis applies to */
  language: string
  /** Per-segment dynamics results */
  segmentDynamics: SegmentDynamicsResult[]
  /** Total scene duration with all extensions applied */
  totalDuration: number
  /** Total extension time added across all segments */
  totalExtension: number
  /** Number of segments in each mode */
  modeCounts: Record<SegmentDynamicsMode, number>
  /** Whether any segment requires freeze-frame extension */
  hasFreeze: boolean
}
